### ISSUE TITLE
The === live demo is ambiguous

### ISSUE THREAD

**Issue by DominoPivot** [nem035/js-equality-algorithms#2]
The live demo comparison acts as if x and y were the same object if you select the same option on both sides. However, this is highly counter-intuitive.

When I ran the comparison `[] === []` I expected it to return false, but it returned true because the example actually passes the same array to both sides. Same goes for all other non-primitive comparisons.

**Comment by nem035** [comment]
Hey, I appreciate the suggestion. When I designed the tool I thought it would seem obvious that the choices are limited to the two sets (primitive, and non-primitive) and that the user selects out of those. I'll try to think of a way to allow comparisons for both equal and different references.

**Comment by nem035** [comment]
[Solved](https://github.com/nem035/js-equality-algorithms/commit/5722f444851c244da995dab0b7963396ead5bdf9)
